version: "3.8"
services:
  cleanplate-database:
    container_name: cleanplate-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: whwlsgkr7/cleanplate-database
    environment:
      - MYSQL_DATABASE=cleanplate
      - MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"

  cleanplate-app:
    container_name: cleanplate-app
    build: .
    depends_on:
      - cleanplate-database
    image: whwlsgkr7/cleanplate-app
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_EXPIREDTIME_MS=${JWT_EXPIREDTIME_MS}
      - JWT_SECRET-KEY=${JWT_SECRET-KEY}
      - OPENAI_SECRET-KEY=${OPENAI_SECRET-KEY}
      - PUBLIC_DATA_API-KEY=${PUBLIC_DATA_API-KEY}
    ports:
      - "80:8080"
    restart: always