#spring.application.name=cleanplate
debug: false
management.endpoints.web.exposure.include: "*" # spring Boot Actuator? ?? ?????? ??? ??

logging:
  level:
    com.myproject.cleanplate: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clean_plate
    username: jinhak
    password: 9943
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # data.sql? ??
    show-sql: true    # ??? ??? ??
    hibernate.ddl-auto: create # DB ?? ???