debug: false
management.endpoints.web.exposure.include: "*" # spring Boot Actuator의 모든 엔드포인트를 웹에서 노출


logging:
  level:
    com.myproject.cleanplate: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.146.63:3306/clean_plate
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

   
  jpa:
    open-in-view: true
    defer-datasource-initialization: true # data.sql가 실행
    show-sql: true    # 쿼리를 콘솔에 출력
    hibernate.ddl-auto: update # DB 자동 초기화

    properties:
      hibernate.format_sql: true # 콘솔에 출력되는 쿼리를 보기 좋게 포맷팅
      hibernate.default_batch_fetch_size: 100
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  sql.init.mode: always # data.sql을 언제 작동시킬것인가

jwt:
  secret-key: ${JWT_SECRET-KEY}
  expired-time-ms: ${JWT_EXPIREDTIME_MS}


publicData:
    secretKey: ${PUBLIC_DATA_API-KEY}


openai.url:
  model: "https://api.openai.com/v1/models"
  model-list: "https://api.openai.com/v1/models/"
  legacy-prompt: "https://api.openai.com/v1/completions"
  prompt: "https://api.openai.com/v1/chat/completions"

openai.secretKey: ${OPENAI_SECRET-KEY}

--- # 새로운 document

spring:
  config.activate.on-profile: testdb


